// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASprUgR7X9NXVlIA2bWKc_e_qf5fsk0h0',
    appId: '1:66712068876:web:73c02fffaa670d70fd9f29',
    messagingSenderId: '66712068876',
    projectId: 'ecommerce-16932',
    authDomain: 'ecommerce-16932.firebaseapp.com',
    storageBucket: 'ecommerce-16932.firebasestorage.app',
    measurementId: 'G-GEYMK0MCW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0scIJZr-W-px3n5C_uRb0DQUANyj288A',
    appId: '1:66712068876:android:1f515da836b28906fd9f29',
    messagingSenderId: '66712068876',
    projectId: 'ecommerce-16932',
    storageBucket: 'ecommerce-16932.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWE49r8GT6hJP8mkkVyr8T7bAEJPAuaDA',
    appId: '1:66712068876:ios:ffdbf24b0dd9c9f2fd9f29',
    messagingSenderId: '66712068876',
    projectId: 'ecommerce-16932',
    storageBucket: 'ecommerce-16932.firebasestorage.app',
    iosBundleId: 'com.once.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWE49r8GT6hJP8mkkVyr8T7bAEJPAuaDA',
    appId: '1:66712068876:ios:ffdbf24b0dd9c9f2fd9f29',
    messagingSenderId: '66712068876',
    projectId: 'ecommerce-16932',
    storageBucket: 'ecommerce-16932.firebasestorage.app',
    iosBundleId: 'com.once.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASprUgR7X9NXVlIA2bWKc_e_qf5fsk0h0',
    appId: '1:66712068876:web:0af323dc144621bffd9f29',
    messagingSenderId: '66712068876',
    projectId: 'ecommerce-16932',
    authDomain: 'ecommerce-16932.firebaseapp.com',
    storageBucket: 'ecommerce-16932.firebasestorage.app',
    measurementId: 'G-7V8GHEL9ZW',
  );
}
